ci: update to kilted

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,31 +2,48 @@ name: Tag & Release
 
 on:
   workflow_dispatch:
+    inputs:
+      build_kilted:
+        type: boolean
+        default: true
+        description: "Release for Kilted"
+
+      build_jazzy:
+        type: boolean
+        default: true
+        description: "Release for Jazzy"
 
 jobs:
+  setup:
+    runs-on: ubuntu-latest
+    outputs:
+      distros: ${{ steps.set-distros.outputs.distros }}
+    steps:
+      - id: set-distros
+        run: |
+          distros=()
+          [ "${{ github.event.inputs.build_jazzy }}" == "true" ] && distros+=("jazzy")
+          [ "${{ github.event.inputs.build_kilted }}" == "true" ] && distros+=("kilted")
+
+          if [ ${#distros[@]} -eq 0 ]; then
+            echo "::error::No distros selected. Please enable release for at least one of the available distros."
+            exit 1
+          fi
+
+          echo "distros=$(jq -cn '$ARGS.positional' --args "${distros[@]}")" >> $GITHUB_OUTPUT
+
   release:
     strategy:
       fail-fast: true
       matrix:
+        ros_distro: ${{ steps.set-distros.outputs.distros }}
         job:
-          - runner: buildjet-4vcpu-ubuntu-2204
+          - runner: 4vcpu-ubuntu-2404
             arch: amd64
-            ros_distro: iron
-            github_release: true
-          - runner: buildjet-4vcpu-ubuntu-2204-arm
+          - runner: 4vcpu-ubuntu-2404-arm
             arch: arm64
-            ros_distro: iron
-            github_release: false
-          - runner: buildjet-4vcpu-ubuntu-2204
-            arch: amd64
-            ros_distro: jazzy
-            github_release: false
-          - runner: buildjet-4vcpu-ubuntu-2204-arm
-            arch: arm64
-            ros_distro: jazzy
-            github_release: false
 
-    name: Release - ${{ matrix.job.arch }}
+    name: Release - ${{ matrix.job.arch }} - ${{ matrix.ros_distro }}
     runs-on: ${{matrix.job.runner}}}
 
     steps:
@@ -38,7 +55,7 @@ jobs:
         with:
           token: ${{ secrets.API_TOKEN_GITHUB }}
           arch: ${{ matrix.job.arch }}
-          ros_distro: ${{ matrix.job.ros_distro }}
+          ros_distro: ${{ matrix.ros_distro }}
           github_release: ${{ matrix.job.github_release }}
           public: true
           changelog: false
